# Generated by Django 3.2 on 2021-07-22 12:57
from django.db import migrations
from django.utils import timezone


def fill_empty_dates(apps, schema_editor):
    Place = apps.get_model('location', 'Place')
    for place in Place.objects.filter(received_at=None):
        place.received_at = timezone.now
        place.save()


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0002_alter_place_received_at'),
    ]

    operations = [
        migrations.RunPython(fill_empty_dates),
    ]
