# Generated by Django 3.2 on 2021-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20210722_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='received_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата получения координат'),
        ),
    ]
