# Generated by Django 3.2 on 2021-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20210522_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработанный'), ('not_processed', 'Необработанный')], default='not_processed', max_length=20),
        ),
    ]
