# Generated by Django 3.2 on 2021-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20210712_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('not_defined', 'Не определен'), ('cash', 'Наличными'), ('on_website', 'Оплата на сайте')], db_index=True, default='not_defined', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
